version: '3'

networks:
  version-dev:
    driver: bridge
    ipam:
      driver: default

services:

  mongodb-dev:
    image: 'mongo:latest'
    container_name: timesheetmongodbdev
    environment:
      - MONGO_LOG_DIR=/dev/null
    ports:
      - '57017:27017'
    volumes:
      - /home/danial/timesheetMongo:/data/db
    restart: unless-stopped
    networks:
      - version-dev

  timesheet-dev:
    image: d4n14l/timesheet-module:latest
    container_name: timesheetdev
    restart: always
    depends_on:
      - mongodb-dev
    networks:
      - version-dev