spring:
  application:
    name: timesheet
  data:
    mongodb:
      database: timesheet_database
      host: timesheetmongodbdev
      port: 27017

server:
  port: 8082
  url: 141.11.246.224

app-config:
  clientId:
    "397300109176-efllj9hjd6tmmq7b0pk11mbqpl64fm2e.apps.googleusercontent.com"